Implement basic Bus Manager functionality.
siarheishut/route_manager pull request #1
Opened 2023-04-12 22:10 UTC by siarheishut

Process init requests:
- Bus <busname> : <stop >|- ...>.
- Stop <stopname>: <latitude>, <longitude>. Process stat request:
- Bus <busname>.

Tested with unit-tests and manually.

2023-04-12 22:57 UTC, foxfrikses requested changes

2023-04-12 22:57 UTC, foxfrikses commented on src/main.cpp
> +void ProcessRequest(std::ostream &os, BusManager &bm, const Request &request) {
I would rather move ```ProcessRequest``` to a separate file in order to be able to test this function.

2023-04-12 22:57 UTC, foxfrikses commented on src/main.cpp
> +void ProcessRequest(std::ostream &os, BusManager &bm, const Request &request) {
```const BusManager &bm```

2023-04-12 22:57 UTC, foxfrikses commented on src/main.cpp
> +void ProcessRequest(std::ostream &os, BusManager &bm, const Request &request) {
It's better to order arguments in a way that input-args are listed first, and output-arguments are listed the last. So, I recommend it to be:
```ProcessRequest(const BusManager &bm, const Request &request, std::ostream &os)```

2023-04-12 22:57 UTC, foxfrikses commented on src/main.cpp
> +    BusResponse rs = bm.GetBusInfo(ptr_b->bus);
nit: how about renaming ```rs``` to ```response``` or ```resp```.

2023-04-12 22:57 UTC, foxfrikses commented on src/main.cpp
> +}
nit: add an empty line in the end of the file.

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +std::ostream &operator<<(std::ostream &out, const BusResponse &response);
Why do we need this operator here?

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +#include <iostream>
Is not required here.

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +#include <set>
Not used.

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +#include <variant>
Not used.

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +  void AddStop(const std::string &stop,
```std::string stop```, as you are anyway going to move it inside.

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +  void AddBus(const std::string &bus, std::vector<std::string> &stops);
The same, as with the stop.

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +  void AddBus(const std::string &bus, std::vector<std::string> &stops);
```std::vector<std::string> &stops``` means, that stops is input-output parameter. But it's only input parameter. So, I would suggest making it either ```const std::vector<std::string> &stops``` or ```std::vector<std::string> stops```. Depending on the use.

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +  std::from_chars(rc.data(), rc.data() + rc.size(), output_request_count);
Add check for [from_chars](https://en.cppreference.com/w/cpp/utility/from_chars) return code.

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +      requests.emplace_back(ParseBusOutput(sv));
push_back

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +std::pair<std::vector<Request>, std::vector<Request>>
I would rather created a dedicated structure for this. Let's say, ```struct Requests{vector<Request> input, output;};```

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +#include <variant>
not used

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +#include <iostream>
Maybe istream would be enough?

2023-04-12 22:57 UTC, foxfrikses commented on src/bus_manager.h
> +#endif // ROOT_MANAGER_SRC_BUS_MANAGER_H_
Add an empty line.

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.h
> +std::vector<Request> RequestReaderInput(std::istream &in);
Function name should start with a verb, describing what the function dose. This function doesn't request anything, but rather reads.

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.h
> +std::vector<Request> RequestReaderOutput(std::istream &in);
Same as above.

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.h
> +#include <iostream>
Maybe istream?

2023-04-12 22:57 UTC, foxfrikses commented on src/request_reader/request_reader.h
> +#endif // ROOT_MANAGER_SRC_REQUEST_READER_H_
Empty end line.

2023-04-13 11:33 UTC, foxfrikses requested changes

2023-04-13 11:33 UTC, foxfrikses commented on src/request_reader/request_split.cpp
> +  bool is_circular = sv[sv.find_first_of("->")] == '>';
Maybe it makes sense to add a check for the string being mis-formatted: if it doesn't have a single - or > character.

2023-04-13 11:33 UTC, foxfrikses commented on src/utils.h
> +
You don't need an empty line here.

2023-04-13 11:33 UTC, foxfrikses commented on src/utils.h
> +#include <string_view>
Include should be outside of a namespace.

2023-04-13 11:33 UTC, foxfrikses commented on tests/request_processor.h
> +}
As it's a duplicate of the function from main, it'd be better to move this function to a separate file under src and use it both in root_manager and in tests.

2023-04-13 11:33 UTC, foxfrikses commented on tests/request_processor.h
> +#ifndef ROOT_MANAGER_SRC_REQUEST_PROCESSOR_H_
This file in not under src directory, so it should be ```ROOT_MANAGER_TESTS_REQUEST_PROCESSOR_H_```

2023-04-13 11:33 UTC, foxfrikses commented on tests/end_to_end_test.cpp
> +
No empty line required

2023-04-13 11:33 UTC, foxfrikses commented on CMakeLists.txt
> +# tests end
empty line in the end

2023-04-13 17:06 UTC, foxfrikses commented on src/bus_manager.h
> +  void AddStop(const std::string &stop,
But it's supposed to be moved, isn't it? You use it as ```data[stop]```, but could have done ```data[std::move(stop)]``` instead

2023-04-13 17:11 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +  std::from_chars(rc.data(), rc.data() + rc.size(), output_request_count);
How about making it 
```
if (auto ec = std::from_chars(rc.data(), rc.data() + rc.size(), 
                                                  input_request_count).second;
    ec != std::errc()) {
  throw SOME_ERROR;
}
```
Or any other way to provide the user with the information about the error occurred.

2023-04-13 17:21 UTC, foxfrikses commented on src/request_reader/request_reader.h
> +std::vector<Request> RequestReaderInput(std::istream &in);
How about making it ```ReadInputRequests```, in plural?

2023-04-13 17:25 UTC, foxfrikses commented on src/bus_manager.h
> +  void AddBus(const std::string &bus, std::vector<std::string> &stops);
The same, as with the stop.

2023-04-13 20:51 UTC, siarheishut commented on src/bus_manager.h
> +  void AddStop(const std::string &stop,
Done.

2023-04-13 20:51 UTC, siarheishut commented on src/utils.h
> +#include <string_view>
Done.

2023-04-13 20:51 UTC, siarheishut commented on src/utils.h
> +
Removed.

2023-04-13 20:51 UTC, siarheishut commented on src/request_reader/request_types.h
> +bool operator!=(const PostStopRequest &lhs, const PostStopRequest &rhs);
Done.

2023-04-13 20:51 UTC, siarheishut commented on tests/end_to_end_test.cpp
> +
Done.

2023-04-13 20:51 UTC, siarheishut commented on tests/end_to_end_test.cpp
> +
Done.

2023-04-13 20:57 UTC, siarheishut commented on src/request_reader/request_reader.h
> +std::vector<Request> RequestReaderOutput(std::istream &in);
Done.

2023-04-13 20:57 UTC, siarheishut commented on tests/request_processor.h
> +}
Done.

2023-04-13 20:59 UTC, siarheishut commented on src/request_reader/request_split.h
> +#endif //ROOT_MANAGER_SRC_REQUEST_SPLIT_H_
Done.

2023-04-13 21:00 UTC, siarheishut commented on src/request_reader/request_split.cpp
> +      br.stops.emplace_back(br.stops[i]);
Done.

2023-04-13 21:00 UTC, siarheishut commented on src/request_reader/request_split.cpp
> +  bool is_circular = sv[sv.find_first_of("->")] == '>';
Done.

2023-04-13 21:05 UTC, siarheishut commented on tests/request_processor.h
> +#ifndef ROOT_MANAGER_SRC_REQUEST_PROCESSOR_H_
Deleted file.

2023-04-13 21:09 UTC, siarheishut commented on src/bus_manager.h
> +  void AddBus(const std::string &bus, std::vector<std::string> &stops);
Done.

2023-04-13 21:59 UTC, foxfrikses requested changes

2023-04-13 21:59 UTC, foxfrikses commented on src/bus_manager.h
> +  static double CalculateDistance(Coords lhs, Coords rhs);
You can move ```CalculateDistance``` to cpp file, it doesn't need to be a class member.

2023-04-13 21:59 UTC, foxfrikses commented on src/bus_manager.cpp
> +  if (it == bus_info_.end()) return BusResponse{-1, -1, -1};
How about ```std::optional<BusResponse>``` as a return value.

2023-04-13 21:59 UTC, foxfrikses commented on src/bus_manager.cpp
> +  auto &bus_info = bus_info_.at(bus);
Reuse it, that you found previously.

2023-04-13 21:59 UTC, foxfrikses commented on src/bus_manager.cpp
> +  int stop_count, unique_stop_count;
Declare them where you initialize them.

2023-04-13 21:59 UTC, foxfrikses commented on src/bus_manager.cpp
> +  }
Maybe it'd be easier to make methods: ```AddBus```, ```AddStop```,  – which just add info about bus and stop; and after that call methods ```ComputeDistances``` and ```ComputeStopCounts```, which will compute all the distances?

2023-04-13 21:59 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +  if (ec != std::errc()) return {};
This code is duplicated in ```ReadOutputRequests```, it should be generalized.

2023-04-13 21:59 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +      requests.push_back(ParsePostBusRequest(sv));
```emplace_back```, as ```requests``` is a vector of ```PostRequest```, which needs to be constructed from ```PostBusRequest``` or ```PostStopRequest```.
The same with ```ParsePostStopRequest``` and ```ParseGetBusRequest```.

2023-04-13 21:59 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +  return {std::move(requests.input), std::move(requests.output)};
```return Requests{.input = ReadInputRequests(in), .output = ReadOutputRequests(in)};```

2023-04-13 21:59 UTC, foxfrikses commented on src/request_reader/request_split.cpp
> +  if (pos == sv.npos) return PostBusRequest{.bus = "", .stops = {}};
Maybe then ```std::optional<PostBusRequest>```

2023-04-13 21:59 UTC, foxfrikses commented on src/request_reader/request_split.cpp
> +  return GetBusRequest{.bus = (std::string) ReadNextToken(sv, "")};
```std::string(ReadNextToken(sv, ""))```

2023-04-13 21:59 UTC, foxfrikses commented on tests/test_utils.cpp
> +  out << br.bus << ": " << br.stops << std::endl;
```operator<<``` shouldn't place ```std::endl``` in the end.
Also ```return out << br.bus << ": " << br.stops;``` in one line.
Same for ```PostStopRequest``` and ```PostStopRequest```.

2023-04-13 21:59 UTC, foxfrikses commented on src/request_reader/request_split.h
Why is this file called ```request_split```?
Maybe it should be a part of ```request_reader```?

2023-04-14 11:09 UTC, foxfrikses requested changes

2023-04-14 11:09 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +  sr.coords.latitude = std::stod(std::string(ReadNextToken(sv, ",")));
```std::stod``` will throw an exception if there is invalid token. In this case you should catch this exception and the whole PostStopRequest will become invalid. So, maybe it worths it to return ```std::optional``` here too?

2023-04-14 11:09 UTC, foxfrikses commented on src/request_reader/request_reader.cpp
> +  return GetBusRequest{.bus = (std::string(ReadNextToken(sv, "")))};
I believe it'd be better to have ```std::optional``` here too, as ```bus``` may be empty.

2023-04-14 11:09 UTC, foxfrikses commented on src/request_reader/request_types.h
It looks like you don't need ```request_reader``` folder after all. Don't you think?

2023-04-14 11:30 UTC, foxfrikses requested changes

2023-04-14 11:30 UTC, foxfrikses commented on src/bus_manager.cpp
> +}
It doesn't need to be marked as ```static```. Plus, you don't need it in ```rm``` namespace. I'd moved it to an unnamed namespace: 
```
namespace {
// Used the solution from https://stackoverflow.com/a/70429229.
// Uses Haversine formula https://en.wikipedia.org/wiki/Haversine_formula
// with asin expressed with atan2 for better accuracy.
double CalculateDistance(Coords lhs, Coords rhs) {
  constexpr double earth_radius_m = 6371.0 * 1000.0;

  const double d_lat = rhs.latitude - lhs.latitude;
  const double d_long = rhs.longitude - lhs.longitude;

  double a =
      std::sin(d_lat / 2) * std::sin(d_lat / 2) + std::sin(d_long / 2) *
          std::sin(d_long / 2) *
          std::cos(lhs.latitude) *
          std::cos(rhs.latitude);
  double c = earth_radius_m * 2 * std::atan2(std::sqrt(a), std::sqrt(1 - a));

  return c;
} 
} //  namespace
```

2023-04-14 12:40 UTC, siarheishut commented on src/request_processor.cpp
> +       << bus_resp.length << " route length\n";
Done.

2023-04-14 12:40 UTC, siarheishut commented on src/bus_manager.cpp
> +}
Done.

2023-04-14 12:40 UTC, siarheishut commented on src/bus_manager.cpp
> +  if (it == bus_info_.end()) return {};
Done.

2023-04-14 12:40 UTC, siarheishut commented on src/request_reader/request_reader.cpp
> +}
Why do we need to check this ```ptr != sv.end()```?

2023-04-14 13:14 UTC, siarheishut commented on tests/request_reader_test.cpp
> +TEST(TestRequestReader, TestRequests) {
Done.

2023-04-14 13:29 UTC, siarheishut commented on src/request_reader/request_reader.cpp
> +}
Done.

2023-04-14 13:37 UTC, foxfrikses requested changes

2023-04-14 13:37 UTC, foxfrikses commented on src/request_reader.cpp
> +      requests.emplace_back(ParsePostBusRequest(sv).value());
> If *this contains a value, returns a reference to the contained value.
> Otherwise, throws a [std::bad_optional_access]
> -- <cite>[std::optional::value()](https://en.cppreference.com/w/cpp/utility/optional/bad_optional_access)</cite> 

So, you should check for value to be set, and only then call emplace.

2023-04-14 13:37 UTC, foxfrikses commented on src/request_reader.cpp
> +  std::string bus = std::string(ReadNextToken(sv, ""));
You don't need to convert the token you read to string here. Only if it's not empty, right before storing it to the request.

2023-04-14 13:37 UTC, foxfrikses commented on src/request_reader.cpp
> +  sr.stop = ReadNextToken(sv, ":");
How about checking stop for empty?

2023-04-14 13:37 UTC, foxfrikses commented on src/request_reader.cpp
> +  br.bus = ReadNextToken(sv, ":");
How about checking bus for empty?

2023-04-14 13:37 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +    std::vector<PostRequest> want_input;
Maybe `want`, not `want_input`?

2023-04-14 13:37 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +          .want_output = {}
Maybe `input` and `want`? Not `output` and `want_output`.

2023-04-14 15:48 UTC, siarheishut commented on src/bus_manager.cpp
> +  }
Done.

2023-04-15 18:46 UTC, siarheishut commented on src/request_reader/request_reader.cpp
> +  std::from_chars(rc.data(), rc.data() + rc.size(), output_request_count);
Will implement in later commits.

2023-04-15 21:58 UTC, foxfrikses requested changes
I haven't finished reviewing request_reader_test.cpp yet. Will come back to it later.

2023-04-15 21:58 UTC, foxfrikses commented on src/bus_manager.h
> +  void AddStop(const std::string &stop,
Okay, let's leave it as const& for now

2023-04-15 21:58 UTC, foxfrikses commented on src/bus_manager.h
> +              const std::vector<std::string> &stops);
`std::vector<std::string> stops`

2023-04-15 21:58 UTC, foxfrikses commented on src/bus_manager.h
> +  explicit BusManager(const std::vector<PostRequest> &requests);
Maybe it makes sense to receive it as `std::vector<PostRequest> requests`, as you will move a lot of data inside anyway.

2023-04-15 21:58 UTC, foxfrikses commented on src/main.cpp
> +  for (auto &request : output_requests) {
How about `for (auto &request : ReadOutputRequests(std::cin))`

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.cpp
> +        requests.emplace_back(ParsePostStopRequest(sv).value());
Don't need to call Parse twice.
`value()` returns `const&`, whereas `operator*` returns `&`.

`requests.emplace_back(std::move(*sr));`
Same for bus.

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.cpp
> +      if (auto sr = ParsePostStopRequest(sv); sr)
Just `if (auto sr = ParsePostStopRequest(sv))`
Same for bus.

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.cpp
> +        requests.emplace_back(br.value());
Same as in `ReadInputRequests`

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.cpp
> +    br.stops.emplace_back(ReadNextToken(sv, "->"));
Make `stop1 - stop2 > stop3` and `stop1 > stop2 - stop3` be errors, and add tests, checking it

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.cpp
> +    for (int i = br.stops.size() - 2; i >= 0; --i)
Let's make `stop1 - stop2 - stop1 -` produce an error: if last stop is empty, then it's an invalid request.

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.cpp
> +    for (int i = br.stops.size() - 2; i >= 0; --i)
Make error, if `stops.size() < 2`

2023-04-15 21:58 UTC, foxfrikses commented on src/request_reader.h
> +
You can move it to cpp into an unnamed namespace.

2023-04-15 21:58 UTC, foxfrikses commented on tests/test_utils.h
> +bool CompareLength(double lhs, double rhs);
`CompareLength(double lhs, double rhs, int precision)`

2023-04-15 21:58 UTC, foxfrikses commented on tests/test_utils.cpp
> +  out << std::endl;
Don't need it

2023-04-15 21:58 UTC, foxfrikses commented on tests/test_utils.cpp
> +  return out;
`return out << br.stop_count << ' ' << br.unique_stop_count << ' ' << br.length;`

2023-04-15 21:58 UTC, foxfrikses commented on tests/test_utils.cpp
> +  return out;
`return out << br.bus;`

2023-04-15 21:58 UTC, foxfrikses commented on tests/test_utils.cpp
> +  return out;
`return out << sr.stop << ": " << std::setprecision(6) << sr.coords.latitude << ' ' << std::setprecision(6) << sr.coords.longitude;`

2023-04-15 21:58 UTC, foxfrikses commented on tests/test_utils.cpp
> +  return out;
`return out << br.bus << ": " << br.stops;`

2023-04-15 21:58 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +    BusManager test_item;
You can make it `vector<GetRequest> test_item` and construct `BusManager` based on it for every test below.

2023-04-15 21:58 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +      TestCase{
Verify "bus: stop1 > stop2 > stop3" to make nullopt.
Verify "bus: stop1 > stop1" to be correct, as well as "bus: stop1 - stop2".

2023-04-15 21:58 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +          .name = "Wrong format: no stop delimiter",
Maybe let's name the test `one stop`.

2023-04-15 21:58 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +          .name = "Test 1",
Let's give these tests more meaningful names.

2023-04-15 23:40 UTC, siarheishut commented on src/request_reader.cpp
> +    for (int i = br.stops.size() - 2; i >= 0; --i)
Done.

2023-04-15 23:40 UTC, siarheishut commented on src/request_reader.h
> +
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +    BusManager test_item;
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/request_reader_test.cpp
> +          .name = "Wrong format: no stop delimiter",
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/request_reader_test.cpp
> +      TestCase{
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/request_reader_test.cpp
> +          .name = "Test 1",
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/test_utils.cpp
> +  out << std::endl;
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/test_utils.cpp
> +  return out;
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/test_utils.cpp
> +  return out;
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/test_utils.cpp
> +  return out;
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/test_utils.cpp
> +  return out;
Done.

2023-04-15 23:40 UTC, siarheishut commented on tests/test_utils.h
> +bool CompareLength(double lhs, double rhs);
Done.

2023-04-16 03:39 UTC, foxfrikses requested changes

2023-04-16 03:39 UTC, foxfrikses commented on tests/test_utils.cpp
> +             << std::setprecision(6) << sr.coords.longitude;
You can unite these lines.

2023-04-16 03:39 UTC, foxfrikses commented on src/request_reader.cpp
> +    return std::nullopt;
Let's move this to the top of the function.

2023-04-16 03:39 UTC, foxfrikses commented on src/request_reader.cpp
> +  if (pos1 != sv.npos && pos2 != sv.npos)
`if (pos1 != sv.npos ^ pos2 != sv.npos)`
Let's use xor. This way we make sure, that one and only one of symbols - and > is present in the string.

2023-04-16 03:39 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +                  want[i]->length << '\n' << got->length;
```<< "want: " << want[i]->length << ", got: " << got->length;```?

2023-04-16 05:02 UTC, foxfrikses requested changes

2023-04-16 13:53 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +    std::vector<rm::PostRequest> test_item;
Done.

2023-04-16 13:53 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +      EXPECT_EQ(p1, p2) << "end_to_end test – " << name;
Done.

2023-04-16 13:53 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +          .want = {rm::BusResponse{5, 3, 20939.5},
Done.

2023-04-16 14:04 UTC, siarheishut commented on tests/request_reader_test.cpp
> +  };
Done.

2023-04-16 15:52 UTC, foxfrikses requested changes

2023-04-16 15:52 UTC, foxfrikses commented on src/request_reader.cpp
> +std::optional<double> ReadDouble(std::string_view sv) {
Let's make `ToInt` and `ReadDouble` named consistently: either `ToInt`, `ToDouble`; or `ReadInt` and `ReadDouble`.

2023-04-16 15:52 UTC, foxfrikses commented on src/request_reader.cpp
> +  }
You don't need `try-catch` here.

2023-04-16 15:52 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +TEST(TestParsePostStopRequest, TestPSR) {
Let's make other names, as discussed offline.
Abbreviations should be written in camel case.

2023-04-16 15:54 UTC, siarheishut commented on tests/request_reader_test.cpp
> +TEST(TestParsePostStopRequest, TestPSR) {
Done.

2023-04-16 15:54 UTC, siarheishut commented on src/request_reader.cpp
> +  }
Done.

2023-04-16 15:54 UTC, siarheishut commented on src/request_reader.cpp
> +std::optional<double> ReadDouble(std::string_view sv) {
Done.

2023-04-16 15:58 UTC, foxfrikses approved these changes
LGTM

2023-04-16 15:59 UTC, merged