Add a dedicated library for json.
siarheishut/route_manager pull request #12
Opened 2023-05-07 21:34 UTC by siarheishut

2023-05-07 23:35 UTC, foxfrikses requested changes

2023-05-07 23:35 UTC, foxfrikses commented on lib/json/src/json.cpp
Send this as a separate commit, and add tests for output.

2023-05-07 23:35 UTC, foxfrikses commented on lib/json/include/json.h
>  #include <ostream>
remove rm namespace

2023-05-07 23:35 UTC, foxfrikses commented on CMakeLists.txt
> +
extra line

2023-05-07 23:35 UTC, foxfrikses commented on lib/json/tests/tests.cpp
Delete these tests from rm.

2023-05-07 23:43 UTC, siarheishut commented on CMakeLists.txt
> +
Done.

2023-05-07 23:43 UTC, siarheishut commented on lib/json/include/json.h
>  #include <ostream>
Done.

2023-05-07 23:43 UTC, siarheishut commented on lib/json/src/json.cpp
Will be done.

2023-05-07 23:43 UTC, siarheishut commented on lib/json/tests/tests.cpp
Done.

2023-05-08 00:01 UTC, foxfrikses approved these changes
LGTM

2023-05-08 00:01 UTC, merged