Add FindRoute method.
siarheishut/route_manager pull request #16
Opened 2023-05-08 13:22 UTC by siarheishut

2023-05-08 13:29 UTC, foxfrikses commented on lib/json/include/json.h
Why are there any changes in json lib?

2023-05-08 16:11 UTC, foxfrikses requested changes

2023-05-08 16:11 UTC, foxfrikses commented on src/request_processor.cpp
> +  }
I suggest moving this to an external function.

2023-05-08 16:11 UTC, foxfrikses commented on src/request_processor.cpp
> +    if (auto ptr_w = std::get_if<RouteBase::RouteInfo::WaitItem>(&item)) {
Let's use `has_alternative` and `get`, so it'll be possible to move data out from json.

2023-05-08 16:11 UTC, foxfrikses commented on src/request_processor.cpp
> +    response.emplace("error_message", std::string("not found"));
Please fix this type of errors in a separate commit and cover them with tests.

2023-05-08 16:11 UTC, foxfrikses commented on src/request_processor.cpp
> +                           std::vector<GetRequest> requests) {
If you receive it by value, that implies that you're going to modify data inside this container. So, you now can use `holds_alternative` and `get` and move date to `Process*Request` functions

2023-05-08 16:11 UTC, foxfrikses commented on src/request_processor.h
> +#include "lib/json/include/json.h"
?

2023-05-08 16:11 UTC, foxfrikses commented on src/request_processor.h
> +                           std::vector<GetRequest> request);
If you receive this by value, maybe then you should receive `Get*Request` by value in all these three functions?

2023-05-08 16:11 UTC, foxfrikses commented on src/route_base/route_base.cpp
> +    distance += rm::sphere::CalculateDistance(stops[i - 1], stops[i]);
In line 11 you use `rm::sphere`, but in line 25 you use `sphere`. Please, make it consistent.

2023-05-08 16:11 UTC, foxfrikses commented on src/route_base/route_base.cpp
> +  vertices_.resize(count);
```
: settings_(routing_settings), graph_(stop_info.size() * 2),
  vertices_(stop_info.size() * 2) {
```

2023-05-08 17:54 UTC, siarheishut commented on lib/graph/src/graph.h
> +#ifndef GRAPH_GRAPH_H_
Done.

2023-05-09 10:32 UTC, siarheishut commented on src/request_parser.cpp
> +#include "lib/json/include/json.h"
Deleted.

2023-05-09 10:34 UTC, siarheishut commented on src/request_parser.cpp
> +  RoutingSettings rs;
Done.

2023-05-09 10:34 UTC, siarheishut commented on src/request_parser.h
> +#include "lib/json/include/json.h"
Deleted.

2023-05-09 10:46 UTC, siarheishut commented on src/request_processor.h
> +#include "lib/json/include/json.h"
Deleted.

2023-05-09 11:00 UTC, siarheishut commented on src/request_processor.cpp
> +  }
Done.

2023-05-09 11:11 UTC, siarheishut commented on src/request_processor.cpp
> +    if (auto ptr_w = std::get_if<RouteBase::RouteInfo::WaitItem>(&item)) {
Done.

2023-05-09 11:15 UTC, siarheishut commented on src/request_processor.cpp
> +                           std::vector<GetRequest> requests) {
Done.

2023-05-09 11:17 UTC, siarheishut commented on src/request_processor.h
> +                           std::vector<GetRequest> request);
Done.

2023-05-09 11:18 UTC, siarheishut commented on src/route_base/route_base.cpp
> +    distance += rm::sphere::CalculateDistance(stops[i - 1], stops[i]);
Done.

2023-05-09 11:19 UTC, siarheishut commented on src/route_base/route_base.cpp
> +  vertices_.resize(count);
Done.

2023-05-10 13:53 UTC, siarheishut commented on src/request_processor.cpp
> +    response.emplace("error_message", std::string("not found"));
Done.

2023-05-10 21:35 UTC, foxfrikses commented on src/sphere.h
> +// with asin expressed with atan2 for better accuracy.
I think you better move this to .cpp file

2023-05-11 09:43 UTC, siarheishut commented on src/sphere.h
> +// with asin expressed with atan2 for better accuracy.
Done.

2023-05-13 17:42 UTC, siarheishut commented on CMakeLists.txt
> +        src/route_base/route_base.cpp
Because I have tests for method FindRoute, which uses it.

2023-05-13 17:42 UTC, siarheishut commented on src/sphere.h
> +#include <cmath>
Done.

2023-05-13 17:43 UTC, siarheishut commented on src/request_parser.h
> +std::optional<RoutingSettings> ParseSettings(json::Dict settings);
Done.

2023-05-13 17:44 UTC, siarheishut commented on src/request_processor.cpp
> +  } else return json::Dict{};
Deleted.

2023-05-13 17:47 UTC, siarheishut commented on src/request_types.h
> +using BusDict = std::unordered_map<std::string, BusInfo>;
Done.

2023-05-13 17:51 UTC, siarheishut commented on src/route_base/route_base.cpp
> +  const auto count = stop_info.size() * 2;
Done.

2023-05-13 17:54 UTC, siarheishut commented on src/route_base/route_base.cpp
> +  router_ = std::make_unique<Router>(std::move(graph_));
Fixed.

2023-05-13 18:03 UTC, siarheishut commented on src/sphere.h
> +#include "request_types.h"
Done.

2023-05-21 16:13 UTC, foxfrikses requested changes

2023-05-21 16:13 UTC, foxfrikses commented on src/route_base/route_base.h
> +  std::unique_ptr<Router> router_;
Could you please add a comment for `Router` class about what algorithm for computing the shortest paths is used, when the computation is done (on initialization or for each request), what the complexity of each method is, and what memory usage of the class is?

2023-05-21 16:13 UTC, foxfrikses commented on src/route_base/route_base.h
> +double ComputeGeoDistance(const std::vector<rm::sphere::Coords> &stops);
Let's make `ComputeGeoDistance` work with `const std::vector<std::string> &stops, const StopDict &dict` as well

2023-05-21 16:13 UTC, foxfrikses commented on src/route_base/route_base.h
> +    };
Let's move it out of Route base, as you did with stopInfo and BusInfo

2023-05-21 16:13 UTC, foxfrikses commented on tests/request_parser_test.cpp
> +#include "lib/json/include/json.h"
?

2023-05-21 16:22 UTC, siarheishut commented on src/route_base/route_base.h
> +    std::vector<Item> items;
Done.

2023-05-21 16:23 UTC, siarheishut commented on src/sphere.h
> +double CalculateDistance(Coords lhs, Coords rhs);
Done.

2023-05-21 16:29 UTC, siarheishut commented on src/route_base/route_base.cpp
> +  auto vertex_to = stop_to_ids_[to].arrive;
Done.

2023-05-21 16:29 UTC, siarheishut commented on src/bus_manager.cpp
> +    return std::nullopt;
Done.

2023-05-21 16:33 UTC, siarheishut commented on src/route_base/route_base.h
> +class RouteBase {
Done.

2023-05-21 16:35 UTC, siarheishut commented on src/bus_manager.h
> +#include "src/route_base/route_base.h"
Removed

2023-05-21 16:35 UTC, siarheishut commented on src/bus_manager.h
> +  explicit BusManager(std::vector<PostRequest> requests,
Done.

2023-05-21 16:41 UTC, siarheishut commented on src/request_parser.cpp
> +    sr.stop_distances.emplace(stop, dist.AsInt());
We can't move map's key.

2023-05-21 16:50 UTC, siarheishut commented on src/request_processor.cpp
> +  }
Done.

2023-05-21 16:51 UTC, siarheishut commented on src/request_types.h
> +#include <unordered_map>
Deleted.

2023-05-21 16:52 UTC, siarheishut commented on src/request_types.h
> +#include <set>
Deleted.

2023-05-21 17:08 UTC, siarheishut commented on src/route_base/route_base.h
> +    };
Done.

2023-05-21 17:09 UTC, siarheishut commented on tests/request_parser_test.cpp
> +#include "lib/json/include/json.h"
Deleted.

2023-05-21 17:38 UTC, siarheishut commented on src/route_base/route_base.h
> +  std::unique_ptr<Router> router_;
Done.

2023-05-26 02:13 UTC, siarheishut commented on src/bus_manager.cpp
> +  route_base_ =
Done.

2023-05-26 02:18 UTC, siarheishut commented on src/bus_manager.cpp
> +  rm::BusInfo bus_info;
Done.

2023-05-26 02:22 UTC, siarheishut commented on src/bus_manager.h
> +  std::unique_ptr<RouteManager> route_base_;
Done.

2023-05-26 02:23 UTC, siarheishut commented on src/route_manager.h
> +  };
Done.

2023-05-26 02:29 UTC, siarheishut commented on src/route_manager.h
> +  std::unordered_map<std::string, StopIds> stop_to_ids_;
Renamed `stop_to_ids_` to `stop_ids`, but left `vector<Vertex> vertices_`.

2023-05-26 02:34 UTC, siarheishut commented on src/route_manager.h
> +  // edges in the route.
Fixed. Moved to above `class Router`. It seems right to me.

2023-05-26 02:41 UTC, siarheishut commented on src/route_manager.h
> +using BusDict = std::unordered_map<std::string, BusInfo>;
Done.

2023-05-26 02:48 UTC, siarheishut commented on src/route_manager.h
> +                           const StopDict &dict);
Done.

2023-05-26 02:54 UTC, siarheishut commented on src/bus_manager.cpp
>    bus_info_[std::move(bus)] = bus_info;
Done.

2023-06-09 16:21 UTC, foxfrikses requested changes
Will approve after fixing the comments left.

2023-06-09 16:21 UTC, foxfrikses commented on src/route_manager.cpp
> +
nit: extra line

2023-06-09 16:21 UTC, foxfrikses commented on src/route_manager.h
> + public:
Please add an empty space before each public/private section

2023-06-09 16:21 UTC, foxfrikses commented on src/route_manager.h
> + private:
You don't need to specify `private` twice

2023-06-09 16:21 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +          .config_settings = {.bus_wait_time = 7, .bus_velocity = 54},
For meaningless `{.bus_wait_time = 7, .bus_velocity = 54}`, used in many places as default template please create a constant like `kTestConfigSettings` and use it instead.

2023-06-09 16:21 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +    bool got = BusManager::Create(config, {}) != nullptr;
Why `{}`, not `config_settings`?

2023-06-09 16:21 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +    RoutingSettings config_settings;
Maybe it'd be better to rename it to `routing_settings` everywhere here?

2023-06-09 16:21 UTC, foxfrikses commented on tests/request_processor_test.cpp
> +  using json::List;
How is the change in lines 10-84 related to this commit?

2023-06-09 16:21 UTC, foxfrikses commented on lib/graph/src/router.h
> +// Router requires V^2, where V is the number of vertices
And please move it to a separate commit, as it's not related to the rest of the code.

2023-06-09 16:46 UTC, siarheishut commented on src/bus_manager.h
> +
Deleted.

2023-06-09 16:46 UTC, siarheishut commented on src/route_manager.cpp
> +
Deleted.

2023-06-09 16:47 UTC, siarheishut commented on src/route_manager.cpp
> +                       .to = depart,
Fixed.

2023-06-09 16:48 UTC, siarheishut commented on src/route_manager.h
> +#define ROOT_MANAGER_SRC_BUS_CATALOG_BUS_CATALOG_H_
Fixed.

2023-06-09 16:50 UTC, siarheishut commented on src/route_manager.h
> + public:
Done.

2023-06-09 16:51 UTC, siarheishut commented on src/route_manager.h
> + private:
Done.

2023-06-09 16:56 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +          .config_settings = {.bus_wait_time = 7, .bus_velocity = 54},
Done.

2023-06-09 17:01 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +    bool got = BusManager::Create(config, {}) != nullptr;
Fixed.

2023-06-09 17:02 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +    RoutingSettings config_settings;
Done.

2023-06-09 17:15 UTC, siarheishut commented on tests/request_processor_test.cpp
> +  using json::List;
It's not related. Created a separate commit.

2023-06-09 17:49 UTC, foxfrikses approved these changes

2023-06-09 17:49 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +          .routing_settings = kTestConfigSettings,
Maybe then `kTestRoutingSettings`?

2023-06-09 17:50 UTC, foxfrikses requested changes
Why is there a commit named mend?

2023-06-09 18:19 UTC, siarheishut commented on lib/graph/src/router.h
> +// Router requires V^2, where V is the number of vertices
Done. Created a separate commit for this.

2023-09-04 19:50 UTC, closed without merging