Fix json output format and add output tests.
siarheishut/route_manager pull request #17
Opened 2023-05-08 18:50 UTC by siarheishut

2023-05-08 19:14 UTC, foxfrikses requested changes

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/src/json.cpp
> +#include <cmath>
Why do you need `cmath`?

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +}
Empty line

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +  };
Please add a few more to test that it writes only 6 numbers. And add with numbers more than $10^7 - 1$ too please

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +      },
negative and zero

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +          .want = "\"\"",
String with just spaces inside

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +          .want = "{\"key 1\":3,\"key 2\":2,\"key 3\":1}",
Add a value of every type here please, including Dict

2023-05-08 19:14 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +          .input = List{12, 14, 2.5, "what"},
Add a value of every type here please, including list

2023-05-09 08:17 UTC, siarheishut commented on lib/json/src/json.cpp
> +#include <cmath>
Function mode is in ```cmath```.

2023-05-09 08:18 UTC, siarheishut commented on lib/json/tests/write_test.cpp
> +}
Done.

2023-05-09 08:25 UTC, siarheishut commented on lib/json/tests/write_test.cpp
> +  };
Done.

2023-05-09 08:27 UTC, siarheishut commented on lib/json/tests/write_test.cpp
> +      },
Done.

2023-05-09 08:37 UTC, siarheishut commented on lib/json/tests/write_test.cpp
> +          .want = "{\"key 1\":3,\"key 2\":2,\"key 3\":1}",
Done.

2023-05-09 08:37 UTC, siarheishut commented on lib/json/tests/write_test.cpp
> +          .input = List{12, 14, 2.5, "what"},
Done.

2023-05-10 21:32 UTC, foxfrikses requested changes

2023-05-10 21:32 UTC, foxfrikses commented on lib/json/src/json.cpp
>      Write(out, value);
`out << ':' << value;`

2023-05-10 21:32 UTC, foxfrikses commented on lib/json/tests/write_test.cpp
> +          .want = "[12,41.7,\"what\",null,{\"key\":[\"value\",4]}]",
Add a list value inside a list too

2023-05-11 10:37 UTC, foxfrikses approved these changes
LGTM

2023-05-11 10:48 UTC, merged