Fix request_processor and add tests for it.
siarheishut/route_manager pull request #19
Opened 2023-05-10 13:53 UTC by siarheishut

2023-05-10 21:22 UTC, foxfrikses requested changes

2023-05-10 21:22 UTC, foxfrikses commented on CMakeLists.txt
> +        tests/test_utils.cpp tests/request_processor_test.cpp)
\n

2023-05-10 21:22 UTC, foxfrikses commented on src/request_processor.cpp
>    json::Dict response;
Let's rename them: `json::Dict response`, `std::optional<BusResponse> response`

2023-05-10 21:22 UTC, foxfrikses commented on src/request_processor.cpp
> +json::Dict ToJson(std::optional<StopResponse> resp, int id) {
same renaming as above

2023-05-10 21:22 UTC, foxfrikses commented on tests/request_processor_test.cpp
> +  using Response = std::optional<rm::StopResponse>;
`ResponseOpt`

2023-05-10 21:22 UTC, foxfrikses commented on tests/request_processor_test.cpp
> +  using Response = std::optional<rm::BusResponse>;
`ResponseOpt`

2023-05-11 09:34 UTC, siarheishut commented on CMakeLists.txt
> +        tests/test_utils.cpp tests/request_processor_test.cpp)
Done.

2023-05-11 09:35 UTC, siarheishut commented on src/request_processor.cpp
>    json::Dict response;
Done.

2023-05-11 09:36 UTC, siarheishut commented on src/request_processor.cpp
> +json::Dict ToJson(std::optional<StopResponse> resp, int id) {
Done.

2023-05-11 09:40 UTC, siarheishut commented on tests/request_processor_test.cpp
> +  using Response = std::optional<rm::StopResponse>;
Done.

2023-05-11 09:40 UTC, siarheishut commented on tests/request_processor_test.cpp
> +  using Response = std::optional<rm::BusResponse>;
Done.

2023-05-11 10:41 UTC, foxfrikses requested changes

2023-05-11 10:41 UTC, foxfrikses commented on tests/request_processor_test.cpp
> +TEST(TestProcessRequests, TestStopRequest) {
```suggestion
TEST(TestProcessRequests, TestStopResponseToJson) {
```

2023-05-11 10:41 UTC, foxfrikses commented on tests/request_processor_test.cpp
> +TEST(TestProcessRequests, TestStopRequest) {
```suggestion
TEST(TestProcessRequests, TestStopResponseToJson) {
```

2023-05-11 10:41 UTC, foxfrikses commented on tests/request_processor_test.cpp
> +TEST(TestProcessRequests, TestBusRequest) {
```suggestion
TEST(TestProcessRequests, TestBusResponseToJson) {
```

2023-05-11 11:54 UTC, foxfrikses approved these changes
LGTM

2023-05-11 12:07 UTC, merged