Added new Bus Manager functionality.
siarheishut/route_manager pull request #2
Opened 2023-04-16 21:22 UTC by siarheishut

Process stat request:

- Stop <stop_name>.

Tested with unit-tests and manually.

2023-04-16 23:57 UTC, foxfrikses requested changes

2023-04-16 23:57 UTC, foxfrikses commented on src/main.cpp
> +      ProcessStopRequest(bm, *ptr_s, std::cout);
As for me, I believe it still makes sense to have `ProcessRequest` function, which would only have
```
if (auto ptr_b = std::get_if<GetBusRequest>(&request))
  ProcessBusRequest(bm, *ptr_b, std::cout);
else if (auto ptr_s = std::get_if<GetStopRequest>(&request))
  ProcessStopRequest(bm, *ptr_s, std::cout);
```

2023-04-16 23:57 UTC, foxfrikses commented on src/bus_manager.h
>    std::unordered_map<std::string, Coords> stop_coords_;
How about creating a struct `StopInfo` and putting all the information, related to a particular stop, in one place?

2023-04-16 23:57 UTC, foxfrikses commented on tests/request_reader_test.cpp
>        },
Let's make it in a different way: let's make it work fine with following and leading spaces. But let's make sure that the tests fail when we have non-digital symbols.

Same for input requests.

2023-04-17 01:40 UTC, siarheishut commented on src/main.cpp
> +      ProcessStopRequest(bm, *ptr_s, std::cout);
Done.

2023-04-17 02:01 UTC, siarheishut commented on src/bus_manager.h
>    std::unordered_map<std::string, Coords> stop_coords_;
Done.

2023-04-17 02:46 UTC, siarheishut commented on tests/request_reader_test.cpp
>        },
Done.

2023-04-17 07:01 UTC, foxfrikses requested changes

2023-04-17 15:37 UTC, siarheishut commented on src/bus_manager.cpp
> +  stop_info_.try_emplace(stop);
Done.

2023-04-17 15:37 UTC, siarheishut commented on src/bus_manager.cpp
> +    stop_info_[stop].buses.emplace(bus);
Done.

2023-04-17 15:37 UTC, siarheishut commented on src/bus_manager.h
> +  std::optional<StopInfo> GetStopInfo(const std::string &stop) const;
Done.

2023-04-17 15:37 UTC, siarheishut commented on src/request_reader.cpp
> +  sv = rm::TrimEnd(rm::TrimStart(sv));
Done.

2023-04-17 15:37 UTC, siarheishut commented on src/request_reader.cpp
> +  std::string_view stop = ReadNextToken(sv, "");
Done.

2023-04-17 15:37 UTC, siarheishut commented on tests/request_reader_test.cpp
> +          .input = "  3\n"
Done.

2023-04-17 19:23 UTC, foxfrikses requested changes

2023-04-17 19:23 UTC, foxfrikses commented on src/bus_manager.cpp
> +  return StopResponse{it->second.buses};
If `it->second.buses.empty()`, can't you just return `StopResponse{it->second.buses};` as well?

2023-04-17 19:23 UTC, foxfrikses commented on src/request_reader.cpp
> +  // If empty "" delim is provided, just trims the string.
Not in front of this line, but in place, where you declare `ReadNextToken`

2023-04-17 19:23 UTC, foxfrikses commented on tests/request_reader_test.cpp
>            .want = {},
And how about adding the same for output requests too?

2023-04-18 01:38 UTC, merged