Add Road Distance between stops
siarheishut/route_manager pull request #3
Opened 2023-04-18 20:23 UTC by siarheishut

New Post Stop Request format:
- Stop X: latitude, longitude, D1m to stop1, D2m to stop2, ... Writes X coordinates and road length from X to stop1 which is D1, to stop2 which is D2 and so on. Road length from stop1 to X is also sets equal to D1 unless this distance is set explicitly when adding stop1.

New Get Bus Request output format:
- Bus X: STOPS_COUNT stops on route, UNIQUE_COUNT unique stops, LENGTH route length, C curvature Now LENGTH is sum of road lengths between stops if it exists and otherwise geo length(straight distance between stops using coordinates). Curvature computes as LENGTH / GEO LENGTH (Always C >= 1).

2023-04-18 22:06 UTC, foxfrikses requested changes

2023-04-19 00:35 UTC, siarheishut commented on src/bus_manager.cpp
> +    auto dists = stop_info_[stop_to].dists;
Done.

2023-04-19 00:35 UTC, siarheishut commented on src/bus_manager.cpp
> +}
Done,

2023-04-19 00:35 UTC, siarheishut commented on src/bus_manager.cpp
>      }
Done.

2023-04-19 00:53 UTC, siarheishut commented on src/request_types.h
> +  std::vector<std::pair<std::string, int>> stops;
Done.

2023-04-19 00:54 UTC, siarheishut commented on src/main.cpp
>      ProcessRequest(bm, req, std::cout);
Done.

2023-04-19 00:56 UTC, siarheishut commented on src/bus_manager.h
> +               const std::vector<std::pair<std::string, int>> &stops);
Declined.

2023-04-19 00:57 UTC, siarheishut commented on src/bus_manager.cpp
> +      stop_info_[stop_to].dists[stop] = dist;
Done.

2023-04-19 04:35 UTC, foxfrikses requested changes

2023-04-19 04:35 UTC, foxfrikses commented on tests/bus_manager_test.cpp
>    };
Move this to a separate commit

2023-04-19 04:35 UTC, foxfrikses commented on tests/bus_manager_test.cpp
> +                  << ", got: " << got->length << '\n' << name;
It'd be better, if you printed name first, and all the other things after. Plus, don't use '\n', use and other separation symbol: `-`, `:`, ...

2023-04-19 04:35 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +          .want = std::nullopt,
1. `stop1: 55.611087, 37.20829, 3900km to stop2` - extra symbol after a number
2. `stop1: 55.611087, 37.20829, 3900mto stop2` - no space between `m` and `to`
3. `stop1: 55.611087, 37.20829, 3900.56m to stop2` - float value

2023-04-19 04:35 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +      },
1. `stop1: -55.574371, -37.6517, 7500m to stop2,` - test case with trailing `,`
2. `stop1: -55.574371, -37.6517,` - test case with trailing `,`

2023-04-19 04:50 UTC, siarheishut commented on tests/bus_manager_test.cpp
>    };
Done.

2023-04-19 04:51 UTC, siarheishut commented on tests/bus_manager_test.cpp
> +                  << ", got: " << got->length << '\n' << name;
Done.

2023-04-19 16:48 UTC, foxfrikses requested changes

2023-04-19 16:48 UTC, foxfrikses commented on tests/request_reader_test.cpp
> +      TestCase{
One more test: `stop1: 55.611087, 37.20829, 3900 m to stop2`

2023-04-19 22:21 UTC, foxfrikses approved these changes
LGTM

2023-04-19 22:22 UTC, merged